args:
  experiment_name: sf_v1_stage1_sub06
  train_data:
  - __LOCAL_CONFIG_DATASET_ROOT__/sub-006_train_va.json
  valid_data:
  - __LOCAL_CONFIG_DATASET_ROOT__/sub-006_test_va.json
  num_workers: 1
