args:
  experiment_name: sf_v3_pathB_p1_sub02
  load: ckpts_5b/sf_v3_pathB_init_sub02
  train_data:
  - __LOCAL_CONFIG_DATASET_ROOT__/sub-0002_train_va.json
  valid_data:
  - __LOCAL_CONFIG_DATASET_ROOT__/sub-0002_test_va.json
  num_workers: 1
